### ISSUE TITLE
Thoughts and questions

### ISSUE THREAD

**Issue by 262media** [krasimir/octomments#18]
In first place, thanks for sharing this project, at a first glance sounds cool.
I do have 2 questions for you:
1- What's wrong about loading Discus and their great (with heavy payload) features only "on demand" ? ( for the visitors who wants to read / write comments )
2 - why does octomments needs me to allow to be able to read and write all my public repository data (and i know it's public) . This includes the following:
-Code
-Issues
-Pull requests
-Wikis
-Settings
-Webhooks and services
-Deploy keys 

Thanks again for sharing
Rui S.

**Comment by krasimir** [comment]
Hey,

> 1- What's wrong about loading Discus and their great (with heavy payload) features only "on demand" ? ( for the visitors who wants to read / write comments )

Sure I can put some more engineering and load Discuss later but this still takes the main tread time to execute. Also I didn't like the _heavy_ block. By _heavy_ I mean big in content size. Too many things are rendered.

> 2 - why does octomments needs me to allow to be able to read and write all my public repository data (and i know it's public)

I'm just changing this. It will be probably just your public information.

**Comment by 262media** [comment]
Looks really good. I'll keep an eye on this project. Thank you once more for sharing

**Comment by eioo** [comment]
Very nice web page I visit this daily.
