### ISSUE TITLE
Can I use Octomments in my React Application

### ISSUE THREAD

**Issue by muco-rolle** [krasimir/octomments#23]

**Comment by krasimir** [comment]
Hey, Octocomments is designed to work outside of the React context but sure you can write a component that initiates it. Something like that:

```js
function Comments() {
  useEffect(() => {
     Octomments({
      github: {
        owner: 'krasimir',
        repo: 'octomments',
      },
      issueNumber: 1,
      renderer: [OctommentsRenderer, '#comments']
    }).init();
  }, []);
  return <div id="comments"></div>;
}
```

The library should be added on the page + you have to be careful on re-rendering the `Component`.

**Comment by muco-rolle** [comment]
Thank you @krasimir

**Comment by muco-rolle** [comment]
What is OctommentsRenderer reffered to?

**Comment by krasimir** [comment]
The [renderer](https://github.com/krasimir/octomments/blob/master/renderer/README.md) is a part of Octomments that is responsible for the UI. I split the core functionality and the visual bit to allow the consumers of the library to have different design.
