### ISSUE TITLE
Utterances

### ISSUE THREAD

**Issue by notshi** [krasimir/octomments#32]
Hey, just wondering how different this is to https://github.com/utterance/utterances

Thanks!

**Comment by krasimir** [comment]
Utterances is a bit different in terms of how it finds the issue. It has a bot that creates the issue if it doesn't exists. Octomments leaves this to the developer. And the UI is different. As far as I know Utterances is mimicking the UI of GitHub while this project renders custom UI allowing the developer to change it. Not sure if that's easy to do in Utterances. It was kinda long time ago when I was checking https://github.com/utterance/utterances

**Comment by notshi** [comment]
Ahh, cool. Thanks for clarifying that!
