### ISSUE TITLE
Missing "/" in step 4 on https://ocs.vercel.app/

### ISSUE THREAD

**Issue by avt613** [krasimir/octomments#37]
When I copied the code into my editor it flagged up this error. The second closing script tag is missing a "/". It should be `</script>` rather than `<script>`

**Comment by krasimir** [comment]
Hey,

can you point me to where this code is?

**Comment by avt613** [comment]
Hi, thanks for the quick response. I hope this screenshot helps.
![Screenshot_20210611_172323](https://user-images.githubusercontent.com/47078235/121718279-0d509c00-cada-11eb-8b58-bfd23b8bab66.png)

**Comment by krasimir** [comment]
Fixed. Thanks. 18c826a
